/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#85f8c4',
        'on-tertiary-fixed-variant': '#005137',
        'on-primary': '#ffffff',
        'on-background': '#191c1d',
        'outline-variant': '#c5c6cd',
        'on-primary-fixed': '#101b30',
        'on-error-container': '#93000a',
        'surface-tint': '#545e76',
        'secondary-fixed': '#cbe7f5',
        'inverse-primary': '#bbc6e2',
        'on-primary-fixed-variant': '#3c475d',
        'error': '#ba1a1a',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#45474d',
        'surface-container-low': '#f3f4f5',
        'surface-container-high': '#e7e8e9',
        'on-tertiary-container': '#1fa072',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#304a55',
        'on-secondary-fixed': '#021f29',
        'surface-container-highest': '#e1e3e4',
        'secondary-container': '#cbe7f5',
        'on-surface': '#191c1d',
        'on-secondary-container': '#4e6874',
        'primary-container': '#1b263b',
        'primary-fixed': '#d7e2ff',
        'surface-bright': '#f8f9fa',
        'error-container': '#ffdad6',
        'background': '#f8f9fa',
        'inverse-surface': '#2e3132',
        'on-primary-container': '#828da7',
        'surface-variant': '#e1e3e4',
        'inverse-on-surface': '#f0f1f2',
        'secondary': '#48626e',
        'outline': '#75777d',
        'surface': '#f8f9fa',
        'on-tertiary': '#ffffff',
        'surface-container': '#edeeef',
        'tertiary': '#00160c',
        'primary-fixed-dim': '#bbc6e2',
        'secondary-fixed-dim': '#afcbd8',
        'primary': '#051125',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#002114',
        'tertiary-container': '#002d1d',
        'tertiary-fixed-dim': '#68dba9',
        'surface-dim': '#d9dadb'
      },
      fontFamily: {
        'headline': ['Inter', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif']
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem'
      },
    },
  },
  plugins: [],
}
